#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "fancy-motd"
name = "Fancy MOTD"
description.en = "Add a nice Message Of The Day when log in console."
description.fr = "Ajoute un message du jour complet au moment de se connecter à la console."

version = "1.0.0~ynh1"

maintainers = ["Mistermasque"]

[upstream]
license = "MIT"
admindoc = "https://github.com/bcyran/fancy-motd"
code = "https://github.com/bcyran/fancy-motd"
fund = "https://github.com/bcyran/fancy-motd/issues"


[integration]
yunohost = ">= 12.0.0"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "500M"
ram.runtime = "50M"

[install]
    [install.disable_default_motd]
    ask.en = "Do you want to disable default MOTD message ?"
    ask.fr = "Souhaitez-vous désactiver le MOTD par défaut ?"
    type = "boolean"
    default = true

[resources]
    [resources.sources.main]
    url = "https://github.com/bcyran/fancy-motd/archive/2391e22c77305b9adefcb136ae5c2b8490e187e4.zip"
    sha256 = "51bdde5ee589f9b2b7b3d921ddf1af314d7add2af980bc5fe0bf0ffa6a9abe6b"
    autoupdate.strategy = "latest_github_commit"

    [resources.install_dir]
    owner = "root:rwx"
    group = "root:rx"

    [resources.apt]
    packages = [
        "figlet",
        "curl",
        "smartmontools",
        "lm-sensors"
    ]