#!/usr/bin/env bash

declare -r INSTALL_DIR='/opt/fancy_motd'

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_print_info --message="Declaring files to be backed up for fancy-motd..."

### N.B. : the following 'ynh_backup' calls are only a *declaration* of what needs
### to be backuped and not an actual copy of any file. The actual backup that
### creates and fills the archive with the files happens in the core after this
### script is called. Hence ynh_backups calls take basically 0 seconds to run.

#=================================================
# BACKUP THE CONF FILES
#=================================================

ynh_backup --src_path="$INSTALL_DIR"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Backup script completed for fancy-motd. (YunoHost will then actually copy those files to the archive)."
