#!/usr/bin/env bash

declare -r INSTALL_DIR='/opt/fancy_motd'

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Installing packages..." --weight=1
ynh_install_app_dependencies figlet curl smartmontools lm-sensors

ynh_script_progression --message="Restoring fancy-motd..." --weight=1
ynh_restore_file --origin_path="$INSTALL_DIR"

ynh_script_progression --message="Install motd config..." --weight=1
ln -sfn "$INSTALL_DIR/motd.sh" "/etc/update-motd.d/30-fancy-motd"

ynh_script_progression --message="Setting permissions..." --weight=1
chown -R root:root "$INSTALL_DIR"
chmod -R -x "$INSTALL_DIR"
chmod -R u=rwX,g=rX,o=rX "$INSTALL_DIR"
chmod +x "$INSTALL_DIR/motd.sh"
chmod +x "$INSTALL_DIR/modules/"*

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for fancy-motd" --last
